//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbhelpdeskEntities : DbContext
    {
        public dbhelpdeskEntities()
            : base("name=dbhelpdeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblarea> tblareas { get; set; }
        public virtual DbSet<tblcalidadservicio> tblcalidadservicios { get; set; }
        public virtual DbSet<tblcoordinacion> tblcoordinacions { get; set; }
        public virtual DbSet<tbldepartamento> tbldepartamentos { get; set; }
        public virtual DbSet<tblevento> tbleventoes { get; set; }
        public virtual DbSet<tblincidente> tblincidentes { get; set; }
        public virtual DbSet<tblinstitucion> tblinstitucions { get; set; }
        public virtual DbSet<tbllugar> tbllugars { get; set; }
        public virtual DbSet<tblmarca> tblmarcas { get; set; }
        public virtual DbSet<tblpregunta> tblpreguntas { get; set; }
        public virtual DbSet<tblpuesto> tblpuestoes { get; set; }
        public virtual DbSet<tblrequerimientoaevento> tblrequerimientoaeventoes { get; set; }
        public virtual DbSet<tblrequerimiento> tblrequerimientos { get; set; }
        public virtual DbSet<tblresponsablequipo> tblresponsablequipoes { get; set; }
        public virtual DbSet<tblrespuesta> tblrespuestas { get; set; }
        public virtual DbSet<tbltipoequipo> tbltipoequipoes { get; set; }
        public virtual DbSet<tbltipoincidencia> tbltipoincidencias { get; set; }
        public virtual DbSet<tblusuario> tblusuarios { get; set; }
        public virtual DbSet<cantidadincidentespordepto> cantidadincidentespordeptoes { get; set; }
        public virtual DbSet<ViewCoordinacion> ViewCoordinacions { get; set; }
        public virtual DbSet<ViewDepartamento> ViewDepartamentos { get; set; }
        public virtual DbSet<ViewEventoConRequerimiento> ViewEventoConRequerimientos { get; set; }
        public virtual DbSet<ViewMarca> ViewMarcas { get; set; }
        public virtual DbSet<ViewRequerimiento> ViewRequerimientos { get; set; }
        public virtual DbSet<ViewTipoIncidencia> ViewTipoIncidencias { get; set; }
        public virtual DbSet<ViewUsuario> ViewUsuarios { get; set; }
        public virtual DbSet<VistaEncuesta> VistaEncuestas { get; set; }
        public virtual DbSet<VistaEquipoReporte> VistaEquipoReportes { get; set; }
        public virtual DbSet<VistaEquipos> VistaEquipos { get; set; }
        public virtual DbSet<VistaEvento> VistaEventos { get; set; }
        public virtual DbSet<VistaIncidente> VistaIncidentes { get; set; }
        public virtual DbSet<VistaPregunta> VistaPreguntas { get; set; }
    
        public virtual ObjectResult<EventosXStatus_Result> EventosXStatus(Nullable<int> status)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventosXStatus_Result>("EventosXStatus", statusParameter);
        }
    
        public virtual ObjectResult<IncidentesXStatus_Result> IncidentesXStatus(Nullable<int> status)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IncidentesXStatus_Result>("IncidentesXStatus", statusParameter);
        }
    
        public virtual ObjectResult<ReqAsignados_Result> ReqAsignados(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReqAsignados_Result>("ReqAsignados", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UltimoEvento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UltimoEvento");
        }
    
        public virtual int cerrarIncidente(Nullable<int> idIn, Nullable<int> tipo, string acci, string solu)
        {
            var idInParameter = idIn.HasValue ?
                new ObjectParameter("idIn", idIn) :
                new ObjectParameter("idIn", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var acciParameter = acci != null ?
                new ObjectParameter("Acci", acci) :
                new ObjectParameter("Acci", typeof(string));
    
            var soluParameter = solu != null ?
                new ObjectParameter("Solu", solu) :
                new ObjectParameter("Solu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cerrarIncidente", idInParameter, tipoParameter, acciParameter, soluParameter);
        }
    
        public virtual int insertarIncidente(Nullable<int> tipo, string desc, Nullable<int> soli, string prio, Nullable<int> stat)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            var soliParameter = soli.HasValue ?
                new ObjectParameter("Soli", soli) :
                new ObjectParameter("Soli", typeof(int));
    
            var prioParameter = prio != null ?
                new ObjectParameter("Prio", prio) :
                new ObjectParameter("Prio", typeof(string));
    
            var statParameter = stat.HasValue ?
                new ObjectParameter("Stat", stat) :
                new ObjectParameter("Stat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertarIncidente", tipoParameter, descParameter, soliParameter, prioParameter, statParameter);
        }
    
        public virtual ObjectResult<numEventosPorMes_Result> numEventosPorMes(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<numEventosPorMes_Result>("numEventosPorMes", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<numEventosPorUsuario_Result> numEventosPorUsuario(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<numEventosPorUsuario_Result>("numEventosPorUsuario", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<numIncidentesPorDepto_Result> numIncidentesPorDepto(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<numIncidentesPorDepto_Result>("numIncidentesPorDepto", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<numIncidentesPorMes_Result> numIncidentesPorMes(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<numIncidentesPorMes_Result>("numIncidentesPorMes", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<numIncidentesPorTipo_Result> numIncidentesPorTipo(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<numIncidentesPorTipo_Result>("numIncidentesPorTipo", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<numIncidentesPorUsuario_Result> numIncidentesPorUsuario(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<numIncidentesPorUsuario_Result>("numIncidentesPorUsuario", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<promedioCalidadPorDepto_Result> promedioCalidadPorDepto(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promedioCalidadPorDepto_Result>("promedioCalidadPorDepto", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<promedioCalidadPorMesEv_Result> promedioCalidadPorMesEv(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promedioCalidadPorMesEv_Result>("promedioCalidadPorMesEv", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<promedioCalidadPorMesIn_Result> promedioCalidadPorMesIn(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promedioCalidadPorMesIn_Result>("promedioCalidadPorMesIn", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<promedioCalidadPorTipoIn_Result> promedioCalidadPorTipoIn(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promedioCalidadPorTipoIn_Result>("promedioCalidadPorTipoIn", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<promedioCalidadPorUsuarioEv_Result> promedioCalidadPorUsuarioEv(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promedioCalidadPorUsuarioEv_Result>("promedioCalidadPorUsuarioEv", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<promedioCalidadPorUsuarioIn_Result> promedioCalidadPorUsuarioIn(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<promedioCalidadPorUsuarioIn_Result>("promedioCalidadPorUsuarioIn", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<requerimientosSinAsignar_Result> requerimientosSinAsignar(Nullable<int> idEvento)
        {
            var idEventoParameter = idEvento.HasValue ?
                new ObjectParameter("idEvento", idEvento) :
                new ObjectParameter("idEvento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<requerimientosSinAsignar_Result>("requerimientosSinAsignar", idEventoParameter);
        }
    
        public virtual ObjectResult<topCincoRecursosMasUsados_Result> topCincoRecursosMasUsados(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<topCincoRecursosMasUsados_Result>("topCincoRecursosMasUsados", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<topCincoRecursosMenosUsados_Result> topCincoRecursosMenosUsados(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<topCincoRecursosMenosUsados_Result>("topCincoRecursosMenosUsados", fechaInicioParameter, fechaFinalParameter);
        }
    }
}
