//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcalidadservicio
    {
        public tblcalidadservicio()
        {
            this.tblrespuestas = new HashSet<tblrespuesta>();
        }
    
        public int idCalidad_Servicio { get; set; }
        public string observacionesServicio { get; set; }
        public Nullable<int> incidente { get; set; }
        public bool statusCal_Servicio { get; set; }
        public Nullable<int> evento { get; set; }
        public Nullable<double> promedioCalidad { get; set; }
    
        public virtual tblevento tblevento { get; set; }
        public virtual tblincidente tblincidente { get; set; }
        public virtual ICollection<tblrespuesta> tblrespuestas { get; set; }
    }
}
