//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmarca
    {
        public tblmarca()
        {
            this.tblresponsablequipoes = new HashSet<tblresponsablequipo>();
            this.tblresponsablequipoes1 = new HashSet<tblresponsablequipo>();
            this.tblresponsablequipoes2 = new HashSet<tblresponsablequipo>();
            this.tblresponsablequipoes3 = new HashSet<tblresponsablequipo>();
        }
    
        public int idMarca { get; set; }
        public string nomMarca { get; set; }
    
        public virtual ICollection<tblresponsablequipo> tblresponsablequipoes { get; set; }
        public virtual ICollection<tblresponsablequipo> tblresponsablequipoes1 { get; set; }
        public virtual ICollection<tblresponsablequipo> tblresponsablequipoes2 { get; set; }
        public virtual ICollection<tblresponsablequipo> tblresponsablequipoes3 { get; set; }
    }
}
