//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrequerimientoaevento
    {
        public int evento { get; set; }
        public int requerimiento { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual tblevento tblevento { get; set; }
        public virtual tblrequerimiento tblrequerimiento { get; set; }
    }
}
