//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblresponsablequipo
    {
        public int idResponEq { get; set; }
        public int responsable { get; set; }
        public int tipoEquipo { get; set; }
        public int marcaEquipo { get; set; }
        public string serieEquipo { get; set; }
        public string memoriaRam { get; set; }
        public string discoDuro { get; set; }
        public int marcaMonitor { get; set; }
        public string serieMonitor { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public int marcaMouse { get; set; }
        public string serieMouse { get; set; }
        public int marcaTeclado { get; set; }
        public string serieTeclado { get; set; }
        public string procesador { get; set; }
    
        public virtual tblmarca tblmarca { get; set; }
        public virtual tblmarca tblmarca1 { get; set; }
        public virtual tblmarca tblmarca2 { get; set; }
        public virtual tblmarca tblmarca3 { get; set; }
        public virtual tblusuario tblusuario { get; set; }
        public virtual tbltipoequipo tbltipoequipo { get; set; }
    }
}
