//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltipoequipo
    {
        public tbltipoequipo()
        {
            this.tblresponsablequipoes = new HashSet<tblresponsablequipo>();
        }
    
        public int idTipoEquipo { get; set; }
        public string nomTipoEquipo { get; set; }
        public bool siMonitor { get; set; }
        public bool siEquipo { get; set; }
        public bool siDiscoDuro { get; set; }
        public bool siMouse { get; set; }
        public bool siTeclado { get; set; }
        public bool siRed { get; set; }
        public bool siRAM { get; set; }
        public bool siProcesador { get; set; }
    
        public virtual ICollection<tblresponsablequipo> tblresponsablequipoes { get; set; }
    }
}
