//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltipoincidencia
    {
        public tbltipoincidencia()
        {
            this.tblincidentes = new HashSet<tblincidente>();
        }
    
        public int idTipoIncidente { get; set; }
        public string nomTipoIncidente { get; set; }
    
        public virtual ICollection<tblincidente> tblincidentes { get; set; }
    }
}
