//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusuario
    {
        public tblusuario()
        {
            this.tbleventoes = new HashSet<tblevento>();
            this.tbleventoes1 = new HashSet<tblevento>();
            this.tbleventoes2 = new HashSet<tblevento>();
            this.tblincidentes = new HashSet<tblincidente>();
            this.tblincidentes1 = new HashSet<tblincidente>();
            this.tblincidentes2 = new HashSet<tblincidente>();
            this.tblresponsablequipoes = new HashSet<tblresponsablequipo>();
        }
    
        public int idUsuario { get; set; }
        public string nomCompleto { get; set; }
        public string nomUsuario { get; set; }
        public string password { get; set; }
        public int tipoUsuario { get; set; }
        public int depto { get; set; }
        public string exTel { get; set; }
        public int area { get; set; }
        public int puesto { get; set; }
        public string correo { get; set; }
        public int institucion { get; set; }
    
        public virtual tblarea tblarea { get; set; }
        public virtual tbldepartamento tbldepartamento { get; set; }
        public virtual ICollection<tblevento> tbleventoes { get; set; }
        public virtual ICollection<tblevento> tbleventoes1 { get; set; }
        public virtual ICollection<tblevento> tbleventoes2 { get; set; }
        public virtual ICollection<tblincidente> tblincidentes { get; set; }
        public virtual ICollection<tblincidente> tblincidentes1 { get; set; }
        public virtual ICollection<tblincidente> tblincidentes2 { get; set; }
        public virtual tblinstitucion tblinstitucion { get; set; }
        public virtual tblpuesto tblpuesto { get; set; }
        public virtual ICollection<tblresponsablequipo> tblresponsablequipoes { get; set; }
    }
}
