//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaEquipos
    {
        public int idResponEq { get; set; }
        public string nomCompleto { get; set; }
        public string nomTipoEquipo { get; set; }
        public string nomMarcaEquipo { get; set; }
        public string serieEquipo { get; set; }
        public string memoriaRam { get; set; }
        public string discoDuro { get; set; }
        public string nomMarcaMonitor { get; set; }
        public string serieMonitor { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public string nomMarcaMouse { get; set; }
        public string serieMouse { get; set; }
        public string nomMarcaTeclado { get; set; }
        public string serieTeclado { get; set; }
        public string procesador { get; set; }
    }
}
