//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcalidadservicio
    {
        public tblcalidadservicio()
        {
            this.tblrespuesta = new HashSet<tblrespuesta>();
        }
    
        public int id { get; set; }
        public string observaciones { get; set; }
        public bool estatus { get; set; }
        public double promedio { get; set; }
        public int fk_idservicio { get; set; }
    
        public virtual ICollection<tblrespuesta> tblrespuesta { get; set; }
    }
}
