//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblevento
    {
        public tblevento()
        {
            this.tblcalidadservicios = new HashSet<tblcalidadservicio>();
            this.tblrequerimientoaeventoes = new HashSet<tblrequerimientoaevento>();
        }
    
        public int idEvento { get; set; }
        public string descripcion { get; set; }
        public int solicitante { get; set; }
        public int responsable { get; set; }
        public int apoyo { get; set; }
        public Nullable<System.DateTime> fecha_Sol { get; set; }
        public Nullable<int> lugar { get; set; }
        public Nullable<int> asistencia_aprox { get; set; }
        public string tipo_evento { get; set; }
        public string acomodo { get; set; }
        public Nullable<System.DateTime> horaIn { get; set; }
        public Nullable<System.DateTime> horaFn { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string observaciones { get; set; }
        public string titulo { get; set; }
    
        public virtual ICollection<tblcalidadservicio> tblcalidadservicios { get; set; }
        public virtual tblusuario tblusuario { get; set; }
        public virtual ICollection<tblrequerimientoaevento> tblrequerimientoaeventoes { get; set; }
        public virtual tbllugar tbllugar { get; set; }
        public virtual tblusuario tblusuario1 { get; set; }
        public virtual tblusuario tblusuario2 { get; set; }
    }
}
