//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblevento
    {
        public tblevento()
        {
            this.tblrecursoasignado = new HashSet<tblrecursoasignado>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int fk_idtipo { get; set; }
        public int fk_idlugar { get; set; }
        public int asistencia { get; set; }
        public int fk_idacomodo { get; set; }
        public System.DateTime fecha_realizacion { get; set; }
        public string observacion { get; set; }
        public int fk_idservicio { get; set; }
    
        public virtual tblacomodo tblacomodo { get; set; }
        public virtual ICollection<tblrecursoasignado> tblrecursoasignado { get; set; }
        public virtual tblservicio tblservicio { get; set; }
        public virtual tbllugar tbllugar { get; set; }
        public virtual tbltipoevento tbltipoevento { get; set; }
    }
}
