//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblequipoasignado
    {
        public int id { get; set; }
        public int fk_idusuario_responsable { get; set; }
        public int fk_idtipoequipo { get; set; }
        public int fk_idmarca_equipo { get; set; }
        public string serie_equipo { get; set; }
        public string ram { get; set; }
        public string disco_duro { get; set; }
        public int fk_idmarca_monitor { get; set; }
        public string serie_monitor { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public int fk_idmarca_mouse { get; set; }
        public string serie_mouse { get; set; }
        public int fk_idmarca_teclado { get; set; }
        public string serie_teclado { get; set; }
        public string procesador { get; set; }
    
        public virtual tblmarca tblmarca { get; set; }
        public virtual tblmarca tblmarca1 { get; set; }
        public virtual tblmarca tblmarca2 { get; set; }
        public virtual tblmarca tblmarca3 { get; set; }
        public virtual tbltipoequipo tbltipoequipo { get; set; }
        public virtual tblusuario tblusuario { get; set; }
    }
}
