//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincidente
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public int prioridad { get; set; }
        public string acciones { get; set; }
        public string solucion { get; set; }
        public int fk_idservicio { get; set; }
    
        public virtual tblservicio tblservicio { get; set; }
        public virtual tbltipoincidencia tbltipoincidencia { get; set; }
    }
}
