//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincidente
    {
        public int id { get; set; }
        public int fk_idtipo { get; set; }
        public int fk_idprioridad { get; set; }
        public string acciones { get; set; }
        public string solucion { get; set; }
        public int fk_idservicio { get; set; }
    
        public virtual tblprioridad tblprioridad { get; set; }
        public virtual tblservicio tblservicio { get; set; }
        public virtual tbltipoincidencia tbltipoincidencia { get; set; }
    }
}
