//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblincidente
    {
        public tblincidente()
        {
            this.tblcalidadservicios = new HashSet<tblcalidadservicio>();
        }
    
        public int numIncidente { get; set; }
        public int tipo { get; set; }
        public string descripcion { get; set; }
        public int solicitante { get; set; }
        public string prioridad { get; set; }
        public Nullable<System.DateTime> fecha_Sol { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> horaIn { get; set; }
        public Nullable<System.DateTime> horaFn { get; set; }
        public Nullable<System.DateTime> fecha_Cierre { get; set; }
        public int soporte { get; set; }
        public string acciones { get; set; }
        public string solucion { get; set; }
        public int seguimiento { get; set; }
    
        public virtual ICollection<tblcalidadservicio> tblcalidadservicios { get; set; }
        public virtual tblusuario tblusuario { get; set; }
        public virtual tblusuario tblusuario1 { get; set; }
        public virtual tblusuario tblusuario2 { get; set; }
        public virtual tbltipoincidencia tbltipoincidencia { get; set; }
    }
}
