//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmarca
    {
        public tblmarca()
        {
            this.tblequipoasignado = new HashSet<tblequipoasignado>();
            this.tblequipoasignado1 = new HashSet<tblequipoasignado>();
            this.tblequipoasignado2 = new HashSet<tblequipoasignado>();
            this.tblequipoasignado3 = new HashSet<tblequipoasignado>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<tblequipoasignado> tblequipoasignado { get; set; }
        public virtual ICollection<tblequipoasignado> tblequipoasignado1 { get; set; }
        public virtual ICollection<tblequipoasignado> tblequipoasignado2 { get; set; }
        public virtual ICollection<tblequipoasignado> tblequipoasignado3 { get; set; }
    }
}
