//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrespuesta
    {
        public int idRespuesta { get; set; }
        public int valorRespuesta { get; set; }
        public int pregunta { get; set; }
        public int calidadServicio { get; set; }
    
        public virtual tblcalidadservicio tblcalidadservicio { get; set; }
        public virtual tblpregunta tblpregunta { get; set; }
    }
}
