//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrecurso
    {
        public tblrecurso()
        {
            this.tblrecursoasignado = new HashSet<tblrecursoasignado>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool cuantificable { get; set; }
    
        public virtual ICollection<tblrecursoasignado> tblrecursoasignado { get; set; }
    }
}
