//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrecursoasignado
    {
        public int fk_idevento { get; set; }
        public int fk_idrequerimiento { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual tblevento tblevento { get; set; }
        public virtual tblrecurso tblrecurso { get; set; }
    }
}
