//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblservicio
    {
        public tblservicio()
        {
            this.tblevento = new HashSet<tblevento>();
            this.tblincidente = new HashSet<tblincidente>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int fk_idusuario_solicitante { get; set; }
        public int fk_idusuario_soporte { get; set; }
        public int fk_idusuario_apoyo { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<System.DateTime> hora_inicial { get; set; }
        public Nullable<System.DateTime> hora_final { get; set; }
        public int fk_idestatus { get; set; }
    
        public virtual tblestatus tblestatus { get; set; }
        public virtual ICollection<tblevento> tblevento { get; set; }
        public virtual ICollection<tblincidente> tblincidente { get; set; }
        public virtual tblusuario tblusuario { get; set; }
        public virtual tblusuario tblusuario1 { get; set; }
        public virtual tblusuario tblusuario2 { get; set; }
    }
}
