//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltipoequipo
    {
        public tbltipoequipo()
        {
            this.tblequipoasignado = new HashSet<tblequipoasignado>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public bool monitor { get; set; }
        public bool equipo { get; set; }
        public bool disco_duro { get; set; }
        public bool mouse { get; set; }
        public bool teclado { get; set; }
        public bool red { get; set; }
        public bool ram { get; set; }
        public bool procesador { get; set; }
    
        public virtual ICollection<tblequipoasignado> tblequipoasignado { get; set; }
    }
}
