//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusuario
    {
        public tblusuario()
        {
            this.tblequipoasignado = new HashSet<tblequipoasignado>();
            this.tblservicio = new HashSet<tblservicio>();
            this.tblservicio1 = new HashSet<tblservicio>();
            this.tblservicio2 = new HashSet<tblservicio>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string nombre_usuario { get; set; }
        public string password { get; set; }
        public int fk_idtipo { get; set; }
        public int fk_iddepto { get; set; }
        public string extension_telefonica { get; set; }
        public int fk_idarea { get; set; }
        public int fk_idpuesto { get; set; }
        public string correo { get; set; }
        public int fk_idinstitucion { get; set; }
        public string apellidos { get; set; }
    
        public virtual tblarea tblarea { get; set; }
        public virtual tbldepartamento tbldepartamento { get; set; }
        public virtual ICollection<tblequipoasignado> tblequipoasignado { get; set; }
        public virtual tblinstitucion tblinstitucion { get; set; }
        public virtual tblpuesto tblpuesto { get; set; }
        public virtual ICollection<tblservicio> tblservicio { get; set; }
        public virtual ICollection<tblservicio> tblservicio1 { get; set; }
        public virtual ICollection<tblservicio> tblservicio2 { get; set; }
        public virtual tbltipousuario tbltipousuario { get; set; }
    }
}
