//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUsuario
    {
        public int idUsuario { get; set; }
        public string nomCompleto { get; set; }
        public string nomUsuario { get; set; }
        public string password { get; set; }
        public string tipoUsuarioString { get; set; }
        public string exTel { get; set; }
        public string nomDepto { get; set; }
        public string nomCoordinacion { get; set; }
        public string nomArea { get; set; }
        public string nomPuesto { get; set; }
        public int tipoUsuario { get; set; }
        public string correo { get; set; }
        public string nomInstitucion { get; set; }
    }
}
