//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_equipos
    {
        public int id { get; set; }
        public string nombre_completo { get; set; }
        public string nomTipoEquipo { get; set; }
        public string nomMarcaEquipo { get; set; }
        public string serie_equipo { get; set; }
        public string memoriaRam { get; set; }
        public string disco_duro { get; set; }
        public string nomMarcaMonitor { get; set; }
        public string serie_monitor { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public string nomMarcaMouse { get; set; }
        public string serie_mouse { get; set; }
        public string nomMarcaTeclado { get; set; }
        public string serie_teclado { get; set; }
        public string procesador { get; set; }
    }
}
