//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_equipos
    {
        public int id { get; set; }
        public string nombre_completo { get; set; }
        public string nomTipoEquipo { get; set; }
        public string nomMarcaEquipo { get; set; }
        public string serie_equipo { get; set; }
        public string memoriaRam { get; set; }
        public string disco_duro { get; set; }
        public string nomMarcaMonitor { get; set; }
        public string serie_monitor { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public string nomMarcaMouse { get; set; }
        public string serie_mouse { get; set; }
        public string nomMarcaTeclado { get; set; }
        public string serie_teclado { get; set; }
        public string procesador { get; set; }
    }
}
