//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_encuestas
    {
        public Nullable<long> numero { get; set; }
        public int id { get; set; }
        public string pregunta { get; set; }
        public bool estatus_pregunta { get; set; }
        public int afinidad { get; set; }
        public int valor { get; set; }
        public int idcalidad { get; set; }
        public string observaciones { get; set; }
        public bool estatus_calidad { get; set; }
        public int idservicio { get; set; }
    }
}
