//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_encuestas
    {
        public Nullable<long> numero { get; set; }
        public int id { get; set; }
        public string pregunta { get; set; }
        public bool estatus_pregunta { get; set; }
        public int valor { get; set; }
        public int idcalidad { get; set; }
        public string observaciones { get; set; }
        public int idservicio { get; set; }
    }
}
