//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_promedio_general
    {
        public Nullable<long> posicion { get; set; }
        public int id { get; set; }
        public Nullable<double> promedio_evento { get; set; }
        public Nullable<double> promedio_incidente { get; set; }
        public Nullable<double> promedioTotal { get; set; }
    }
}
