//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_promedio_general
    {
        public Nullable<long> posicion { get; set; }
        public int id { get; set; }
        public Nullable<double> promedio_evento { get; set; }
        public Nullable<double> promedio_incidente { get; set; }
        public Nullable<double> promedioTotal { get; set; }
    }
}
