//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_recursos_asignados
    {
        public int idevento { get; set; }
        public int idsolicitante { get; set; }
        public Nullable<int> cantidad { get; set; }
        public int asistencia { get; set; }
        public string tipo { get; set; }
        public string acomodo { get; set; }
        public Nullable<System.DateTime> hora_inicial { get; set; }
        public Nullable<System.DateTime> hora_final { get; set; }
        public System.DateTime fecha_realizacion { get; set; }
        public string observacion { get; set; }
        public string nom_evento { get; set; }
        public string nom_lugar { get; set; }
        public string nom_coordinacion { get; set; }
        public string nom_recurso { get; set; }
        public int idrecurso { get; set; }
    }
}
