//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_reporte_equipos
    {
        public int id { get; set; }
        public string nom_tipo_equipo { get; set; }
        public string nom_marca_equipo { get; set; }
        public string serie_equipo { get; set; }
        public string memoria_ram { get; set; }
        public string disco_duro { get; set; }
        public string nom_marca_monitor { get; set; }
        public string serie_monitor { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public string nom_marca_mouse { get; set; }
        public string serie_mouse { get; set; }
        public string nom_marca_teclado { get; set; }
        public string serie_teclado { get; set; }
        public string procesador { get; set; }
        public string nom_completo { get; set; }
        public string nom_area { get; set; }
        public string nom_coordinacion { get; set; }
        public string nom_depto { get; set; }
        public string nom_puesto { get; set; }
    }
}
