//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class vt_usuarios
    {
        public int id { get; set; }
        public string nombre_usuario { get; set; }
        public string nom_completo { get; set; }
        public string password { get; set; }
        public string nom_tipo { get; set; }
        public string extension_telefonica { get; set; }
        public string nom_depto { get; set; }
        public string nom_coordinacion { get; set; }
        public string nom_area { get; set; }
        public string nom_puesto { get; set; }
        public int fk_idtipo { get; set; }
        public string correo { get; set; }
        public string nom_institucion { get; set; }
    }
}
